syntax = "proto3";

package meshtastic;

import "meshtastic/lora_config.proto";

option csharp_namespace = "Meshtastic.Protobufs";
option go_package = "github.com/meshtastic/go/generated";
option java_outer_classname = "DestinationsProtos";
option java_package = "com.geeksville.mesh";
option swift_prefix = "";

message DestinationsConfig {

    message MeshDestination {
        /*
         * The node number for this destination
         */
        uint32 num = 1;

        /*
         * Alternative hop limit to use for this destination (zero represents default)
         */
        optional uint32 hop_limit = 2;

        /*
         * Manual next hop specification for messages to this node (zero represents default)
         */
        optional uint32 next_hop = 3;

        /*
         * Node number of first desired leap node toward this destination (optional).
         * At least one of first_leap or last_leap should be set to a valid node number
         * if leaping is desired.
         */
        optional uint32 first_leap = 4;

        /*
         * Node number of last desired leap node toward this destination (optional).
         * This should ordinarily be the closest reliable node to the destination.
         */
        optional uint32 last_leap = 5;

        /*
         * LoRa modem settings to switch out temporarily for messages sent to this destination.
         */
        optional LoRaConfigLite lora_switch = 6;

    }


    /*
     * Optional default destination for most types of packets that would otherwise be sent to broadcast.
     */
    uint32 default_dest = 1;

    /*
     * Optional destination for nodeinfo messages. Defaults to default_dest (or if none, broadcast).
     */
    uint32 nodeinfo_dest = 2;

    /*
     * Optional destination for telemetry messages. Defaults to default_dest (or if none, broadcast).
     */
    uint32 telemetry_dest = 3;

    /*
     * Optional destination for position messages. Defaults to default_dest (or if none, broadcast).
     */
    uint32 position_dest = 4;

    /*
     * Configuration slots for custom handling of specified destinations
     */
    repeated MeshDestination destinations = 5;

    /*
     * Whether to use leaping or not.
     */
    bool leaps_enabled = 6;

    /*
     * Can be used to specify a dedicated channel to send leap messages on. Intended for backwards compatbility with leap-naive nodes.
     * The leap channel should accordingly not use the default AQ== PSK.
     */
    uint32 leap_channel = 7;

    /*
     * Whether to allow LoRa channel switching for destinations
     */
    bool lora_switch_enabled = 8;

    /*
     * Whether to restrict LoRa channel switching to packets from us (not both acting as intermediate leap node and switching) 
     * so that leaps can be enabled for others without also switch radio settings for others.
     */
    bool only_lora_switch_from_us = 9;

    /*
     * Whether to restrict leaping with LoRa radio setting changes to messages.
     * Only works if only_lora_switch_from_us is not set and the message is decodable.
     */
    bool only_leap_switch_messages = 10;

}