  syntax = "proto3";

package meshtastic;

option csharp_namespace = "Meshtastic.Protobufs";
option go_package = "github.com/meshtastic/go/generated";
option java_outer_classname = "ConfigProtos";
option java_package = "com.geeksville.mesh";
option swift_prefix = "";
  
  /*
   * Lora Config
   */
  message LoRaConfig {
    enum RegionCode {
      /*
       * Region is not set
       */
      UNSET = 0;

      /*
       * United States
       */
      US = 1;

      /*
       * European Union 433mhz
       */
      EU_433 = 2;

      /*
       * European Union 868mhz
       */
      EU_868 = 3;

      /*
       * China
       */
      CN = 4;

      /*
       * Japan
       */
      JP = 5;

      /*
       * Australia / New Zealand
       */
      ANZ = 6;

      /*
       * Korea
       */
      KR = 7;

      /*
       * Taiwan
       */
      TW = 8;

      /*
       * Russia
       */
      RU = 9;

      /*
       * India
       */
      IN = 10;

      /*
       * New Zealand 865mhz
       */
      NZ_865 = 11;

      /*
       * Thailand
       */
      TH = 12;

      /*
       * WLAN Band
       */
      LORA_24 = 13;

      /*
       * Ukraine 433mhz
       */
      UA_433 = 14;

      /*
       * Ukraine 868mhz
       */
      UA_868 = 15;

      /*
       * Malaysia 433mhz
       */
      MY_433 = 16;

      /*
       * Malaysia 919mhz
       */
      MY_919 = 17;

      /*
       * Singapore 923mhz
       */
      SG_923 = 18;

      /*
       * Philippines 433mhz
       */
      PH_433 = 19;

      /*
       * Philippines 868mhz
       */
      PH_868 = 20;

      /*
       * Philippines 915mhz
       */
      PH_915 = 21;

      /*
       * Australia / New Zealand 433MHz
       */
      ANZ_433 = 22;

      /*
       * Kazakhstan 433MHz
       */
      KZ_433 = 23;

      /*
       * Kazakhstan 863MHz
       */
      KZ_863 = 24;

      /*
       * Nepal 865MHz
       */
      NP_865 = 25;

      /*
       * Brazil 902MHz
       */
      BR_902 = 26;
    }

    /*
     * Standard predefined channel settings
     * Note: these mappings must match ModemPreset Choice in the device code.
     */
    enum ModemPreset {
      /*
       * Long Range - Fast
       */
      LONG_FAST = 0;

      /*
       * Long Range - Slow
       * Deprecated in 2.7: Unpopular slow preset.
       */
      LONG_SLOW = 1 [deprecated = true];

      /*
       * Very Long Range - Slow
       * Deprecated in 2.5: Works only with txco and is unusably slow
       */
      VERY_LONG_SLOW = 2 [deprecated = true];

      /*
       * Medium Range - Slow
       */
      MEDIUM_SLOW = 3;

      /*
       * Medium Range - Fast
       */
      MEDIUM_FAST = 4;

      /*
       * Short Range - Slow
       */
      SHORT_SLOW = 5;

      /*
       * Short Range - Fast
       */
      SHORT_FAST = 6;

      /*
       * Long Range - Moderately Fast
       */
      LONG_MODERATE = 7;

      /*
       * Short Range - Turbo
       * This is the fastest preset and the only one with 500kHz bandwidth.
       * It is not legal to use in all regions due to this wider bandwidth.
       */
      SHORT_TURBO = 8;

      /*
       * Long Range - Turbo
       * This preset performs similarly to LongFast, but with 500Khz bandwidth.
       */
      LONG_TURBO = 9;


      /* 
       * Signifier for the absence of a preset
       */
      NO_PRESET = 255;
    }

    /*
     * When enabled, the `modem_preset` fields will be adhered to, else the `bandwidth`/`spread_factor`/`coding_rate`
     * will be taked from their respective manually defined fields
     */
    bool use_preset = 1;

    /*
     * Either modem_config or bandwidth/spreading/coding will be specified - NOT BOTH.
     * As a heuristic: If bandwidth is specified, do not use modem_config.
     * Because protobufs take ZERO space when the value is zero this works out nicely.
     * This value is replaced by bandwidth/spread_factor/coding_rate.
     * If you'd like to experiment with other options add them to MeshRadio.cpp in the device code.
     */
    ModemPreset modem_preset = 2;

    /*
     * Bandwidth in MHz
     * Certain bandwidth numbers are 'special' and will be converted to the
     * appropriate floating point value: 31 -> 31.25MHz
     */
    uint32 bandwidth = 3;

    /*
     * A number from 7 to 12.
     * Indicates number of chirps per symbol as 1<<spread_factor.
     */
    uint32 spread_factor = 4;

    /*
     * The denominator of the coding rate.
     * ie for 4/5, the value is 5. 4/8 the value is 8.
     */
    uint32 coding_rate = 5;

    /*
     * This parameter is for advanced users with advanced test equipment, we do not recommend most users use it.
     * A frequency offset that is added to to the calculated band center frequency.
     * Used to correct for crystal calibration errors.
     */
    float frequency_offset = 6;

    /*
     * The region code for the radio (US, CN, EU433, etc...)
     */
    RegionCode region = 7;

    /*
     * Maximum number of hops. This can't be greater than 7.
     * Default of 3
     * Attempting to set a value > 7 results in the default
     */
    uint32 hop_limit = 8;

    /*
     * Disable TX from the LoRa radio. Useful for hot-swapping antennas and other tests.
     * Defaults to false
     */
    bool tx_enabled = 9;

    /*
     * If zero, then use default max legal continuous power (ie. something that won't
     * burn out the radio hardware)
     * In most cases you should use zero here.
     * Units are in dBm.
     */
    int32 tx_power = 10;

    /*
     * This controls the actual hardware frequency the radio transmits on.
     * Most users should never need to be exposed to this field/concept.
     * A channel number between 1 and NUM_CHANNELS (whatever the max is in the current region).
     * If ZERO then the rule is "use the old channel name hash based
     * algorithm to derive the channel number")
     * If using the hash algorithm the channel number will be: hash(channel_name) %
     * NUM_CHANNELS (Where num channels depends on the regulatory region).
     */
    uint32 channel_num = 11;

    /*
     * If true, duty cycle limits will be exceeded and thus you're possibly not following
     * the local regulations if you're not a HAM.
     * Has no effect if the duty cycle of the used region is 100%.
     */
    bool override_duty_cycle = 12;

    /*
     * If true, sets RX boosted gain mode on SX126X based radios
     */
    bool sx126x_rx_boosted_gain = 13;

    /*
     * This parameter is for advanced users and licensed HAM radio operators.
     * Ignore Channel Calculation and use this frequency instead. The frequency_offset
     * will still be applied. This will allow you to use out-of-band frequencies.
     * Please respect your local laws and regulations. If you are a HAM, make sure you
     * enable HAM mode and turn off encryption.
     */
    float override_frequency = 14;

    /*
     * If true, disable the build-in PA FAN using pin define in RF95_FAN_EN.
     */
    bool pa_fan_disabled = 15;

    /*
     * For testing it is useful sometimes to force a node to never listen to
     * particular other nodes (simulating radio out of range). All nodenums listed
     * in ignore_incoming will have packets they send dropped on receive (by router.cpp)
     */
    repeated uint32 ignore_incoming = 103;

    /*
     * If true, the device will not process any packets received via LoRa that passed via MQTT anywhere on the path towards it.
     */
    bool ignore_mqtt = 104;

    /*
     * Sets the ok_to_mqtt bit on outgoing packets
     */
    bool config_ok_to_mqtt = 105;
  }


  /*
   * Simplified Lora Config for switching between presets
   */
  message LoRaConfigLite {
    /*
     * Modem preset to select
     */
    LoRaConfig.ModemPreset modem_preset = 1;

    /*
     * LoRa frequency channel slot to use.
     * 65535 is treated as "unset" for some purposes.
     */
    uint32 channel_num = 2;
  }